### ISSUE TITLE
Issue on executing "MVN Package" build 

### ISSUE THREAD

**Issue by RahulChandrashekar17061984** [schierlm/private-iota-testnet#14]
Hi,

When i execute the MVP Package on the folder, i get the below error

Downloading from bintray-iotaledger-maven: https://dl.bintray.com/iotaledger/maven/org/iota/jota/0.9.10/jota-0.9.10.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.137 s
[INFO] Finished at: 2018-03-05T10:55:46+05:30
[INFO] Final Memory: 10M/191M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project iota-testnet-tools: Could not resolve dependencies for project org.iota:iota-testnet-tools:jar:0.1-SNAPSHOT: Failed to
 collect dependencies at org.iota:jota:jar:0.9.10: Failed to read artifact descriptor for org.iota:jota:jar:0.9.10: Could not transfer artifact org.iota:jota:po
m:0.9.10 from/to bintray-iotaledger-maven (https://dl.bintray.com/iotaledger/maven): sun.security.validator.ValidatorException: PKIX path building failed: sun.s
ecurity.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by schierlm** [comment]
What Java version are you using? Probably you have to update it (or at least the `$JAVA_HOME/{jre/,}lib/security/cacerts` file).

Background: Maven uses that file to check HTTPS certificates, and it seems your copy of `cacerts` does not include the GeoTrust root certificate used by https://dl.bintray.com/

(When you are used to `keytool` you can also download the certificate with your browser and add it to `cacerts` manually. But there should not be a need since the official `cacerts` file of recent Oracle Java packages contains it).

Please tell me if that solves your problem so that I can close the issue.

**Comment by RahulChandrashekar17061984** [comment]
I am using the JRE "1.8.0_92_64". Kindly share me the link where i can download the cacerts for Maven

**Comment by schierlm** [comment]
I don't think Oracle provides indiviidual downloads for certificates (or even `cacerts` files). Find here the `cacerts` file that comes with 1.8.0_161.
[cacerts-8u161.zip](https://github.com/schierlm/private-iota-testnet/files/1786657/cacerts-8u161.zip). 

Otherwise update your Java version or manually install the attached GeoTrust certificate [using `keytool`](https://stackoverflow.com/a/27928213/90203): 

[GeoTrust.cer.zip](https://github.com/schierlm/private-iota-testnet/files/1786674/GeoTrust.cer.zip)



In case you are on a Debian/Ubuntu related Linux machine, you can also reinstall the `ca-certificates-java` package to update your ca certificates.

**Comment by RahulChandrashekar17061984** [comment]
Hi,
I tried updating the certificates,
But i am still getting the same error.
I am using Win 7 OS

[ERROR] Failed to execute goal on project iota-testnet-tools: Could not resolve dependencies for project org.iota:iota-testnet-tools:jar:0.1-SNAPSHOT: F
 collect dependencies at org.iota:jota:jar:0.9.10: Failed to read artifact descriptor for org.iota:jota:jar:0.9.10: Could not transfer artifact org.iota
m:0.9.10 from/to bintray-iotaledger-maven (https://dl.bintray.com/iotaledger/maven): sun.security.validator.ValidatorException: PKIX path building faile
ecurity.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by schierlm** [comment]
Can you try to open the link https://dl.bintray.com/iotaledger/maven in a browser and look at the certificate there? In Internet Explorer, you can click on the padlock icon in the address bar, then "View Certificate".

Certification path should look like this:
![image](https://user-images.githubusercontent.com/1568931/37112412-9cbe6136-2242-11e8-89c9-78294ada48af.png)

When it looks differently, check if you are using some proxy or antivirus solution that tries to "break up" SSL connections - if so, you probably have to add their "fake CA certificate" to cacerts as well.

When you are seeing the correct same certificate, and certification path, make sure that the Java version you updated is indeed the Java version used by Maven (in case you have more than one)

**Comment by RahulChandrashekar17061984** [comment]
Pls find the info of the certification path below

[cid:image001.png@01D3B6CF.682F1D40]

**Comment by RahulChandrashekar17061984** [comment]
Pls find the info of the certification path below

[cid:image001.png@01D3B6CF.CBC383F0]
Where can I find “Fake CA Certificates”?

**Comment by schierlm** [comment]
That image in your email somehow got lost, can you please reply on GitHub (just hit Ctrl+V while your screenshot is in the clipboard and GitHup will upload it for you.

**Comment by schierlm** [comment]
That image in your email somehow got lost, can you please reply on GitHub (just hit Ctrl+V while your screenshot is in the clipboard and GitHup will upload it for you.

Or email it to me `schierlm@gmx.de`

**Comment by schierlm** [comment]
Solved via email.
