### ISSUE TITLE
Coordinator Milestone Index Won't Iterate By 1

### ISSUE THREAD

**Issue by rantwijk** [schierlm/private-iota-testnet#16]
Hello, thanks so much for the work you've done.

I've been running a private testnet for a few weeks now and the coordinator seems to be randomly choosing a new milestone index to create instead of iterating by 1, usually between 10 and 1000. I'm using the PeriodicCoordinator flag at 60 seconds. 

Eg. 
380,000 - > 380,575
380,575 - > 381,257
Etc. 

I assume this may be something I'm doing wrong on my end but I'm hoping to fix it as soon as I can. After a week or so it causes the coordinator to hang around Integer.maxValue.

Any guidance would be appreciated.

**Comment by schierlm** [comment]
I have seen this behaviour myself popping up at some point in time, but it never bothered me (since I don't run the coordinator periodically and none of my testnets survived for as long as a week). I assume it is caused by the [protection against bundle hashes that contain letter M](https://iota.stackexchange.com/questions/1241/why-is-the-normalized-hash-considered-insecure-when-containing-the-char-m) which will increase obsoleteTag in that case until it finds a matching hash. Since the obsoleteTag is at the same time used as the milestone index, it may explain these jumps.

iota.lib.java runs through this protection code even for non-value transactions (which should not be needed) such as milestones.

If you are using iota.lib.java only for the Coordinator, you can try [commenting the relevant part](https://github.com/iotaledger/iota.lib.java/blob/master/jota/src/main/java/jota/model/Bundle.java#L125-L134) and recompiling the coordinator.

**Comment by rantwijk** [comment]
Thank you so much! That ended up working perfectly.

```Apr 04, 2018 10:29:45 PM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 348828 created.
Apr 04, 2018 10:30:57 PM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 348829 created.
Apr 04, 2018 10:32:16 PM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 348830 created.
Apr 04, 2018 10:33:21 PM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 348831 created.
Apr 04, 2018 10:34:53 PM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 348832 created.
```

I ended up learning a good deal more about Maven in the process as well. :)

**Comment by automyr** [comment]
Hi, been trying to reproduce what @rantwijk did to solve this issue and cannot get it to work. The problem is that I don't know if what [I changed on iota.java.lib](https://github.com/iotaledger/iota.lib.java/blob/master/jota/src/main/java/jota/model/Bundle.java#L125-L134) is all that's needed or if there are any other lines I need to change.

I have also been having one hell of a time trying to get maven to use the modified lib instead of the one in the central repo, and when I finally got it to work, the private-testnet tools don't seem to import it (or if they do they don't use it correctly?).

```
java -jar target/iota-testnet-tools-0.1-SNAPSHOT-jar-with-dependencies.jar PeriodicCoordinator localhost 14265 10
Exception in thread "main" java.lang.NoClassDefFoundError: jota/IotaAPI$Builder
        at iotatools.PeriodicCoordinator.main(PeriodicCoordinator.java:30)
        at iotatools.Main.main(Main.java:18)
Caused by: java.lang.ClassNotFoundException: jota.IotaAPI$Builder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
```

What I asking is, can you give more detailed steps to reproduce the fix you did? 

Thanks!

**Comment by rantwijk** [comment]
Hello, I ran into the same issue you did, with the NoClasDefFoundError. Getting Maven to use my own version of Jota was a learning process, glad you were able to get that to work. How did you compile the jar file? I had to create a compile goal in the project settings [as shown here](https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven) before it worked, otherwise it wouldn't compile the dependencies into the resulting jar file.

My Jota pom.xml config:
```
<parent>
        <groupId>org.iota</groupId>
        <artifactId>jota-parent</artifactId>
        <version>0.9.11-SNAPSHOT</version>
</parent>

<groupId>org.jota</groupId>
<artifactId>jota</artifactId>
<version>1.0.0</version>
```

Compile goal config (also in pom.xml):
```
<build>
        <plugins>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id> <!-- this is used for inheritance merges -->
                        <phase>package</phase> <!-- bind to the packaging phase -->
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build> 
```

Then compile with `mvn clean compile assembly:single`.

**Comment by rfornea** [comment]
So, just to clarify, that first group of changes was in iota.lib.java/jota/pom.xml, and the second set of changes was also in the same file?  

Do you recall what (if any) changes you had to make to iota.lib/pom.xml, or the private-iota-testnet/pom.xml files?

**Comment by rfornea** [comment]
Sorry, forgot to "@" you.  @rantwijk

**Comment by schierlm** [comment]
Should be sufficient to change the <version> in iota.lib.java's [two](https://github.com/iotaledger/iota.lib.java/blob/master/pom.xml#L7) pom.xml [files](https://github.com/iotaledger/iota.lib.java/blob/master/jota/pom.xml#L8) so something different (and unique) - to avoid other projects to pick up your changed iota.lib.js. I would probably use something like `0.9.11-for-coordinator`.

Then run `mvn install` on iota.lib.java project (after you patched the Bundle.java) to put the compiled artifacts into your local Maven repository.

Afterwards change the version number of [this repo's pom.xml](https://github.com/schierlm/private-iota-testnet/blob/master/pom.xml#L24) to the same number and `mvn clean package` this repo again.

**Comment by rfornea** [comment]
@schierlm, That worked perfectly, thank you!
