### ISSUE TITLE
jota.error.ArgumentException: "entry point failed consistency check" in iri > 1.4.2.4

### ISSUE THREAD

**Issue by jiebanghan** [schierlm/private-iota-testnet#25]
after run "mvn package"
Then start the interactive process:
`java -jar target/iota-testnet-tools-0.1-SNAPSHOT-jar-with-dependencies.jar SnapshotBuilder`
I got Snapshot.txt and copy it  in the same directory as iri-1.4.2.4.jar.
then I run` java -jar iri-1.4.2.4.jar --testnet --testnet-no-coo-validation --snapshot=Snapshot.txt -p 14700`
then I run " java -jar target/iota-testnet-tools-0.1-SNAPSHOT-jar-with-dependencies.jar Coordinator localhost 14700"
it shows belows: 
```
jota.error.ArgumentException: [{"error":"entry point failed consistency check: SLAMHFDPSVMOFVGEBNYOLLTDDYKBMNJTSZNGZHNEAEY9ITMYZYHCIDHOWWYBLMLPESDFRBARJWYSX9999","duration":7}]
        at jota.IotaAPICore.wrapCheckedException(IotaAPICore.java:71)
        at jota.IotaAPICore.getTransactionsToApprove(IotaAPICore.java:303)
        at iotatools.TestnetCoordinator.main(TestnetCoordinator.java:46)
        at iotatools.Main.main(Main.java:16)
Exception in thread "main" java.lang.NullPointerException
        at iotatools.TestnetCoordinator.main(TestnetCoordinator.java:47)
        at iotatools.Main.main(Main.java:16)
```

So ,I need a hand . how to solve it?

**Comment by schierlm** [comment]
I assume this is due to recent tip selection changes (I did not use private testnet since iri 1.4.2.4).

So basically you have two options

1. Try iri 1.4.2.4 if it works better
2. Set a breakpoint in your iri at [this location](https://github.com/iotaledger/iri/blob/master/src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java#L60) and have a look why the walk validator thinks your new milestone is invalid.

I will probably find time to have a look at it at some later day (but probably it can take a few weeks) so I'll leave this issue open so far. In case you find the issue and can fix it, pull requests are appreciated :)

**Comment by jiebanghan** [comment]
I try iri 1.4.2.4 and it does works well indeed .Thank you.

**Comment by schierlm** [comment]
I updated this project to work with iri 1.5.4. While I never ran into the issue you encountered, I fixed some other issues so this issue may be fixed now too.

In case it happens again, feel free to comment or open a new ticket.
