### ISSUE TITLE
i'm unable to build package in Windows 10!

### ISSUE THREAD

**Issue by Sunanda786** [schierlm/private-iota-testnet#28]
i have tried the suggested way to avoid build package error! but still got following error after running command **mvn package** :
` Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project iri: There are test failures.`  
help me to resolve it!!

**Comment by schierlm** [comment]
Please report issues in building iri (as opposed to building the testnet tools) here: https://github.com/iotaledger/iri/issues

Note that since iri 1.4.2.4 it is no longer required to recompile iri, you can instead use the official release and configure it using command line arguments.

You may try to skip tests by passing `-DskipTests` to mvn command line.
