### ISSUE TITLE
PeriodicCoordinator Issue

### ISSUE THREAD

**Issue by rav1112** [schierlm/private-iota-testnet#29]
I m running private testnet  node... As i need to run periodicCordinator. After 3 days milestone doesnt increment. Whats the issue?

**Comment by schierlm** [comment]
Sorry, i have no idea. What value did the milestone reach? Perhaps it jumped at some point and is near the maximum of 1 million?


On the other hand, since the IOTA Foundation published an official way to set up a private tangle now, I might retire this repository anyway, so perhaps instead of trying to figure out why the periodic coordinator fails for you, you might use

https://github.com/iotaledger/compass/blob/master/docs/HOWTO_private_tangle.md

instead.

**Comment by rav1112** [comment]
Error doesn't come while running Periodic Coordinator. But milestone should be incremented but it is not happening it just repeating again and again 2097152 this milestone. 
Also While Running Coordinator it just gives new milestone created.

You can see below for the output.

**While  Running PeriodicCoordinator it gives -----------------

Nov 26, 2018 8:30:48 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:32:07 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:33:21 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:34:44 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:36:01 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:37:12 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:39:03 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:40:20 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:41:39 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:43:00 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.
Nov 26, 2018 8:44:21 AM iotatools.PeriodicCoordinator$1 run
INFO: New milestone 2097152 created.**


**While  Running Coordinator it gives -----------------

New milestone created.**
