### ISSUE TITLE
How to create a Snapshot signature file?

### ISSUE THREAD

**Issue by vikulin** [schierlm/private-iota-testnet#7]
I'm trying to setup several IOTA nodes. Can you please assist me with the Snapshot signature generation? These nodes will work within a private network. Commenting out the signature generation is not an option since I'm going to run performance tests under similar nodes like IOTA mainnet does.

How to create a Snapshot signature file?

Thanks

**Comment by schierlm** [comment]
See here: https://github.com/schierlm/private-iota-testnet#signing-snapshots-and-milestones

**Comment by vikulin** [comment]
What is security parameter for key generation?

28 дек. 2017 г. 8:13 ПП пользователь "Michael Schierl" <
notifications@github.com> написал:

**Comment by schierlm** [comment]
Winternitz scheme uses a security parameter which determines the length of keys and signatures. Normal addresses use a security parameter of 2, and multisig addresses use higher ones. Since snapshot signatues use a security parameter of 3 and milestone signatures only use 1 (probably to make the generation of the 1 million subkeys faster, or to reduce the number of transactions needed for storing a milestone signature), I decided to make it configurable.

That being said, if you use a different security parameter than the verifying code uses, the signature will not be valid.

**Comment by vikulin** [comment]
class KeyfileBuilder:

String[] keys = new String[(1 << pubkeyDepth)];
should be
String[] keys = new String[(1 << pubkeyDepth)+firstIndex];

due to ArrayIndexBoundException

2017-12-28 21:25 GMT+02:00 Michael Schierl <notifications@github.com>:

**Comment by vikulin** [comment]
Git it. It works.

2017-12-28 21:35 GMT+02:00 Vadym Vikulin <vadym.vikulin@gmail.com>:

**Comment by schierlm** [comment]
Nope. FirstIndex + Count (i.e. last index) have to be smaller than 2 ^ pubkeyDepth. So with a pubkeyDepth of 10, the last index may not be bigger than 1048576. When in doubt, just leave the indices away and generate the whole tree :)

**Comment by vikulin** [comment]
What is private static String SNAPSHOT_PUBKEY in class Snapshot? I did
put Public subkey from class SnapshotSigner but validation failed on
if(!Arrays.equals(Converter.trits(SNAPSHOT_PUBKEY), root)) {
                    throw new RuntimeException("Snapshot signature
failed.");
}

2017-12-28 22:29 GMT+02:00 Michael Schierl <notifications@github.com>:

**Comment by schierlm** [comment]
You need to use the public key at the end of the signature file (also output on the console when you create a signature file), not one of the individual subkeys used for signing an individual snapshot.

**Comment by schierlm** [comment]
You need to use the public key at the end of the key file (also output on the console when you create a key file), not one of the individual subkeys used for signing an individual snapshot.

**Comment by vikulin** [comment]
The last question:

What value should be in com.iota.iri.IRI class:
    public static final Hash MAINNET_COORDINATOR = new
Hash("KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU");
    public static final Hash TESTNET_COORDINATOR = new
Hash("XNZBYAST9BETSDNOVQKKTBECYIPMF9IPOZRWUPFQGVH9HJW9NDSQVIPVBWU9YKECRYGDSJXYMZGHZDXCA");

It seems that it is not IOTA addresses.

2017-12-29 0:49 GMT+02:00 Michael Schierl <notifications@github.com>:

**Comment by schierlm** [comment]
If you want to replace MAINNET_COORDINATOR or TESTNET_COORDINATOR depends on whether you want to "run" a mainnet or testnet :-)

The value should be the public key of your Coordinator.key file. It is used both as an "address" in milestone transactions, as well as the private key for validating the signatures. Sending iota to that "address" is futile since there is no "normal" private key for it that could be  used to withdraw them.
